### ISSUE TITLE
[FEATURE] Update to Kustomize v5

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/operator#178]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem or use-case? Please describe.

Kustomize v5 includes several new features, plus breaking API changes that lead up to `kustomize v1` specs. Its first release was way back in February 2023.

### Describe the solution that you would like.

Upgrade the build pipeline to use Kustomize v5. Most notable is the new syntax for `patches` - see https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0 for list of breaking changes.

Potentially related to #139 .

**Comment by qu1queee** [comment]
From refinement, there is no clear deadline on this, as of today.

**Comment by adambkaplan** [comment]
Will be included in #234
