### ISSUE TITLE
[FEATURE] Handle deletion of roles for webhook deployment

### ISSUE THREAD

**Issue by SaschaSchwarze0** [shipwright-io/operator#181]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem or use-case? Please describe.

We shipped Shipwright Build v0.12.0 with a cluster role and a binding for the webhook that are unnecessary. To follow least-privilege principle, we removed them in https://github.com/shipwright-io/build/pull/1448.

The operator must handle the deletion.

### Describe the solution that you would like.

When updating v0.13.0, the operator should delete the clusterrole `shipwright-build-webhook` and the clusterrolebinding `shipwright-build-webhook`.

**Comment by adambkaplan** [comment]
/close

Fixed in #214
