### ISSUE TITLE
[BUG] v0.12.0 does not ship an exact match of build v0.12.0

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/operator#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kubernetes Version

1.26

### Shipwright Version

v0.12.0

### Current Behavior

The `release.yaml` manifest in `kodata` does not match what is published on the corresponding GitHub [release](https://github.com/shipwright-io/build/releases/download/v0.12.0/release.yaml). This makes it challenging to identify future updates to the release manifest.

### Expected Behavior

`release.yaml` for the operator should closely match `release.yaml` published on GitHub.

### Anything else?

When attempting to update `release.yaml` so that it aligns with the published version, unit and e2e tests fail. See #182

**Comment by adambkaplan** [comment]
Root causes of this issue:

- Our `release.yaml` has large CRDs (build APIs have multiple versions)
- The library we use to deploy `release.yaml` does not support server-side apply (see https://github.com/manifestival/manifestival/issues/102). Without this, Kubernetes adds a "last applied configuration" annotation that effectively duplicates the contents of the CRD.

For v0.12.0, this was fixed by manually crafting a `release.yaml` that removed the description fields from our CRDs (which can be quite lengthy).

Until manfiestival supports server-side apply, we can work around this by adding a [Transform](https://github.com/manifestival/manifestival?tab=readme-ov-file#transform) function that truncates the description fields in the CRDs.

**Comment by adambkaplan** [comment]
This issue is going to block #181 (or we need to craft a `release.yaml` which strips out the descriptions of CRD fields).

**Comment by qu1queee** [comment]
From refinement, where are we with this one @adambkaplan  .

**Comment by adambkaplan** [comment]
Updated status - we merged #204 which should unblock us from using the `release.yaml` from the v0.12.0 release.

Alternatively, we use the v0.13.0 release candidate manifest, thereby allowing us to work on #181 (at the same time?)
