### ISSUE TITLE
[SHIP-0038] Use Release Branches for Releasing

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/operator#197]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem or use-case? Please describe.

Per [SHIP-0038](https://github.com/shipwright-io/community/blob/main/ships/0038-release-branching-backports.md), we are changing our release process to ship official releases from a release branch, rather than from main.

### Describe the solution that you would like.

* CI and release scripts can be run on a release branch (with release-v* pattern)
* Release workflows must use an appropriate release branch and/or git reference (cannot blindly use latest commit from main)

### Describe alternatives you have considered.

See [SHIP-0038](https://github.com/shipwright-io/community/blob/main/ships/0038-release-branching-backports.md) for discussion

### Anything else?

Part of https://github.com/shipwright-io/community/issues/85

**Comment by qu1queee** [comment]
@adambkaplan how long does this issue needs to be open? what is missing?

**Comment by adambkaplan** [comment]
I think we call this "Done" when we release v0.13.0 for the operator (or at least a candidate). This is currently blocked by #184 (which we made progress on today).
