### ISSUE TITLE
Standardize `controller-gen` Results

### ISSUE THREAD

**Issue by otaviof** [shipwright-io/operator#23]
[Recently we noticed](https://github.com/shipwright-io/operator/pull/14#discussion_r719580190) the outcomes of [`controller-gen`](https://book.kubebuilder.io/reference/controller-gen.html) can be different on GitHub Actions (Ubuntu based) than on our workstations.

What can we do in order to make sure `controller-gen` will produce the exact same outcomes, regardless where it's being executed?

**Comment by coreydaley** [comment]
https://github.com/kubernetes-sigs/controller-tools/pull/623 was opened by @akram

**Comment by adambkaplan** [comment]
I think this issue was closed - we recently updated controller-gen, and this seems to have addressed the issue.

/close
